TebLocalPlannerROS:
   
 # Trajectory
  
 teb_autosize: True
 dt_ref: 0.3
 dt_hysteresis: 0.1
 global_plan_overwrite_orientation: True
 allow_init_with_backwards_motion: False
 max_global_plan_lookahead_dist: 3.0
 feasibility_check_no_poses: 5
    
 # Robot
         
 max_vel_x: 2.0
 max_vel_x_backwards: 0.2
 max_vel_y: 0.01
 max_vel_theta: 2.0
 acc_lim_x: 2.0
 acc_lim_y: 0.01
 acc_lim_theta: 1.0
 min_turning_radius: 0.3 # omni-drive robot (can turn on place!)
 cmd_angle_instead_rotvel: false

 footprint_model:
   type: "polygon"
   vertices: [[0.175, -0.175], [0.0897,-0.23 ], [0.009,-0.225], [-0.122,-0.15], [-0.24,0.0], [-0.122,0.15], [0.009,0.225], [0.0897,0.23], [0.175,0.175]]
   is_footprint_dynamic: true

 # GoalTolerance
    
 xy_goal_tolerance: 0.3
 yaw_goal_tolerance: 0.5
 free_goal_vel: False
    
 # Obstacles
    
 min_obstacle_dist: 0.6 # This value must also include our robot radius, since footprint_model is set to "point".
 inflation_dist: 0.8
 dynamic_obstacle_inflation_dist: 0.6
 include_costmap_obstacles: True
 include_dynamic_obstacles: True
 costmap_obstacles_behind_robot_dist: 15.0
 obstacle_poses_affected: 30

 # Optimization
    
 no_inner_iterations: 5
 no_outer_iterations: 4
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.05
 weight_max_vel_x: 3
 weight_max_vel_y: 4
 weight_max_vel_theta: 1
 weight_acc_lim_x: 2
 weight_acc_lim_y: 2
 weight_acc_lim_theta: 1
 weight_kinematics_nh: 1 # WE HAVE A HOLONOMIC ROBOT, JUST ADD A SMALL PENALTY
 weight_kinematics_forward_drive: 1
 weight_kinematics_turning_radius: 1
 weight_optimaltime: 1
 weight_obstacle: 50
 weight_inflation: 20.3
 weight_dynamic_obstacle: 50
 weight_dynamic_obstacle_inflation: 0.3
 weight_adapt_factor: 2

 # Homotopy Class Planner

 enable_homotopy_class_planning: True
 enable_multithreading: True
 simple_exploration: False
 max_number_classes: 4
 selection_cost_hysteresis: 1.0
 selection_obst_cost_scale: 1.0
 selection_alternative_time_cost: True
 
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 10
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_keypoint_offset: 0.1
 obstacle_heading_threshold: 0.45
 visualize_hc_graph: False 
 visualize_with_time_as_z_axis_scale: 0.2